In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("Extracted_features.csv")

In [4]:
df.head()

,has_ip,count_dots,count_hyphens,count_at,count_colon,count_slashes,count_question_marks,count_equals,count_and,count_percentage,...,count_occurrences_of_com,count_occurrences_of_www,count_double_slashes,length_without_protocol,longest_repeated_substring,levenshtein_to_common_domain,vowel_consonant_ratio,cluster_label,status,url
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,16,0,9,0.499998,0,benign,lechorepublicain.fr
1,0,2,2,0,1,4,0,0,0,0,...,0,0,1,30,0,9,0.499998,1,malicious,https://bridgtrzr-dcs.github.io/en-us/
2,0,2,0,0,1,3,0,0,0,0,...,0,0,1,15,0,9,0.499998,1,malicious,https://l.ead.me/bfUZQN
3,0,2,4,0,1,7,1,3,2,0,...,1,0,1,165,0,9,0.499998,2,malicious,https://docs.google.com/presentation/d/e/2PACX...
4,0,2,0,0,1,3,1,1,0,0,...,0,0,1,44,0,9,0.499998,1,malicious,https://kyc4w2.webwave.dev/?forcePageWithoutCd...

In [5]:
df.describe()

,has_ip,count_dots,count_hyphens,count_at,count_colon,count_slashes,count_question_marks,count_equals,count_and,count_percentage,...,count_unique_chars,ratio_special_to_total_chars,count_occurrences_of_com,count_occurrences_of_www,count_double_slashes,length_without_protocol,longest_repeated_substring,levenshtein_to_common_domain,vowel_consonant_ratio,cluster_label
count,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,...,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,127656.000000,127656.0,127656.0,1.276560e+05,127656.000000
mean,0.005076,1.528968,0.499859,0.004089,0.509103,1.808587,0.076322,0.222167,0.147984,0.038792,...,17.394889,0.145886,0.530747,0.013435,0.507771,28.958161,0.0,9.0,4.999975e-01,0.669361
std,0.071066,0.907016,1.120614,0.068664,0.526256,2.081501,0.290076,1.070490,0.836477,1.036220,...,12.241279,0.064162,0.529948,0.117551,0.538999,112.607763,0.0,0.0,2.220455e-16,0.882553
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.003487,0.000000,0.000000,0.000000,1.000000,0.0,9.0,4.999975e-01,0.000000
25%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10.000000,0.090909,0.000000,0.000000,0.000000,9.000000,0.0,9.0,4.999975e-01,0.000000
50%,0.000000,1.000000,0.000000,0.000000,0.500000,1.000000,0.000000,0.000000,0.000000,0.000000,...,14.000000,0.135000,1.000000,0.000000,0.500000,14.000000,0.0,9.0,4.999975e-01,1.000000
75%,0.000000,2.000000,1.000000,0.000000,1.000000,3.000000,0.000000,0.000000,0.000000,0.000000,...,20.000000,0.200000,1.000000,0.000000,1.000000,28.000000,0.0,9.0,4.999975e-01,1.000000
max,1.000000,33.000000,50.000000,8.000000,6.000000,104.000000,17.000000,47.000000,43.000000,192.000000,...,73.000000,0.681529,7.000000,3.000000,52.000000,25515.000000,0.0,9.0,4.999975e-01,4.000000